r"""Write the printable and cuttable files for the ring-drive rig.

    python3 scripts/truss/make_rig_cad.py [--out cad]

STL in mm for the 3D-printed parts, DXF (R12) for the two flat parts.
Everything is generated from `spec.Ring` and the chosen truss, so a change
to the solve is a re-run rather than a redraw.  `check_cad` re-derives all
of it and asserts the clearances the layout claims.

WHICH PROCESS, AND WHY.  The ring and the pinions carry involute teeth at
module 0.8 -- 1.26 mm of tooth thickness at the pitch circle and 1.8 mm
whole depth -- so they want a RESIN print, not a 0.4 mm nozzle smearing
four perimeters across a flank.  The plate and the base are slabs whose
only job is to hold three shafts and a motor concentric, and acrylic cut
in one pass is flatter and stiffer than the same shape grown in layers, so
they are DXF.
"""
import sys
import os
from math import degrees

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import numpy as np

from truss import cad
from truss.spec import Ring, Truss, ring_r_out, rail_r_out
from spine import chosen

OUT = "cad"


def _row(name, m, qty, process, note=""):
    lo, hi = m.bbox()
    open_e = len(m.open_edges())
    return dict(name=name, qty=qty, process=process, tris=len(m.tris),
                size=tuple(hi - lo), vol=m.volume(), open=open_e, note=note,
                info=getattr(m, "info", {}))


def main(argv):
    out = OUT
    if "--out" in argv:
        out = argv[argv.index("--out") + 1]
    os.makedirs(out, exist_ok=True)
    t = Truss(**chosen.OPTIMAL_1M.as_truss_kwargs())
    M = Ring.mesh()
    L = cad.axial_layout()
    arcs = cad.race_arcs()
    wide = sorted({round(b - a, 2) for a, b in arcs})
    rows = []

    parts = [("ring", cad.ring(), 1, "resin",
              "48T m0.8, 300 deg of arc, groove in the +z face"),
             ("pinion", cad.pinion(), 3, "resin",
              "18T m0.8 + integral GT2 20T, two MR63 seats")]
    for w in wide:
        tag = "race_long" if w == max(wide) else "race_short"
        n = sum(1 for a, b in arcs if abs((b - a) - w) < 0.01)
        parts.append((tag, cad.race(0.0, w, tag), n, "resin or FDM",
                      "%.2f deg of C-channel" % w))
    parts += [("vjig_chord", cad.vblock(t.d_chord, 25.0, "vjig_chord"), 1,
               "FDM", "V for the %.1f mm chord, axis %.0f mm up"
               % (t.d_chord, cad.H_AXIS)),
              ("vjig_diag", cad.vblock(t.d_diag, 25.0, "vjig_diag"), 1,
               "FDM", "V for the %.1f mm diagonal, axis %.0f mm up"
               % (t.d_diag, cad.H_AXIS))]

    for name, m, qty, proc, note in parts:
        m.stl(os.path.join(out, name + ".stl"))
        rows.append(_row(name, m, qty, proc, note))

    flats = [("plate", cad.plate_dxf(), 1, "%.0f mm acrylic or aluminium"
              % cad.PLATE_T),
             ("base", cad.base_dxf(t.alpha), 1, "%.0f mm acrylic" % cad.BASE_T)]
    for name, d, qty, stock in flats:
        n = d.write(os.path.join(out, name + ".dxf"))
        rows.append(dict(name=name, qty=qty, process="laser: " + stock,
                         tris=n, size=None, vol=None, open=0, note="", info={}))

    belt = cad.belt_path()
    txt = [_manifest(rows, t, M, L, arcs, belt)]
    open(os.path.join(out, "MANIFEST.txt"), "w").write(txt[0])
    print(txt[0])
    return 0


def _manifest(rows, t, M, L, arcs, belt):
    o = []
    w = o.append
    w("RING-DRIVE RIG -- generated by scripts/truss/make_rig_cad.py")
    w("units: mm.  STL is binary.  DXF is R12; layer CUT is the cut path,")
    w("layer SCRIBE is an alignment mark to engrave, NOT to cut through.")
    w("")
    w("SOLVED GEOMETRY THIS WAS BUILT FROM (spec.Ring.mesh())")
    w("  module %.1f   rim %dT pitch r %.2f tip r %.2f   pinion %dT pitch r %.2f"
      % (M.m, M.n_ring, M.r_pitch, ring_r_out(), M.n_pinion, M.r_pinion))
    w("  centre distance %.2f   pinions at %s deg"
      % (M.centre, ", ".join("%.2f" % a for a in Ring.pinion_az())))
    w("  ring gap %.0f deg = %.0f teeth   rail mouth %.2f deg   rail to r %.2f"
      % (Ring.GAP, Ring.teeth_in_gap(), Ring.race_mouth(), rail_r_out()))
    w("  tooth-root stress %.1f MPa of %.0f allowed at SF %.0f"
      % (M.sigma, Ring.PINION_SIGMA, Ring.PINION_SF))
    w("")
    w("THE AXIAL CHAIN (the ring's own axis, mm)")
    w("  ring band        -%.2f .. +%.2f" % (Ring.W / 2, Ring.W / 2))
    w("  rail flanges      %.2f .. %.2f either side" % (L["rail_in"], L["rail_out"]))
    w("  belt band         %.2f .. %.2f   (clears the rail by %.2f)"
      % (L["belt_x0"], L["belt_x0"] + L["belt_band"], L["clear_belt_rail"]))
    w("  plate face        %.2f          (a %.0f mm standoff off the rail)"
      % (L["plate_x"], L["standoff_l"]))
    w("  pinion stack      %.2f tall, gear band at z %.2f .. %.2f"
      % (L["z_top"], L["z_pocket_a"], L["z_gear"]))
    w("")
    w("THE RAIL, IN FOUR ARCS -- a pinion's hub reaches in to r %.2f, which"
      % (M.centre - (M.r_pinion - 1.25 * M.m)))
    w("is inside the flange's own band (r %.2f to %.2f), so each pinion needs"
      % (M.r_pitch - 1.25 * M.m, rail_r_out()))
    w("a window of +-%.2f deg.  check_drive models ONE CONTINUOUS RAIL, so"
      % cad.pinion_window_deg())
    w("the windows are a divergence -- but they are not new dead arc, because")
    w("a pinion is what locates the ring in its own window.")
    for a, b in arcs:
        w("  %7.2f .. %7.2f  (%5.2f deg)" % (a, b, b - a))
    w("")
    w("THE BELT: one loop round the outside of four pulleys, which is what")
    w("phases three pinions off one motor.")
    w("  motor at az %.1f, r %.1f on a %.0f mm radial slot (the tensioner)"
      % (cad.MOTOR_AZ, cad.MOTOR_R, cad.MOTOR_SLOT))
    w("  hull convex: %s   path %.1f mm -> a 220 mm closed loop, 110 teeth"
      % (belt["convex"], belt["length"]))
    w("  standoffs at az %s" % ", ".join("%.1f" % a for a in cad.standoff_az()))
    w("")
    w("PARTS")
    w("  %-12s %3s  %-28s %7s  %-22s %s"
      % ("file", "qty", "process", "tris", "bbox mm", "note"))
    for r in rows:
        sz = ("%.1f x %.1f x %.1f" % r["size"]) if r["size"] else "-"
        w("  %-12s %3d  %-28s %7d  %-22s %s"
          % (r["name"], r["qty"], r["process"], r["tris"], sz, r["note"]))
    w("")
    w("BUY (the rig's own hardware -- the motor, driver and supply are yours)")
    w("  MR63ZZ 3x6x2.5 bearing            6 + spares   two per pinion")
    w("  3 mm ground rod or dowel, 30 mm   3            pinion shafts, pressed")
    w("  GT2 closed-loop belt, 6 mm wide   1            220 mm / 110 teeth")
    w("  GT2 20T pulley, 5 mm bore         1            the motor's own")
    w("  M3 x %.0f mm F-F standoff          6            rail to plate, bonded"
      % L["standoff_l"])
    w("  M3 x 8 screws / M4 x 12           12 / 4       standoffs / base")
    w("")
    w("FITS -- a first article measures these, and they live in one place")
    for k in ("FIT_BEARING", "FIT_SHAFT", "FIT_SCREW", "FIT_PRESS", "FIT_ROD",
              "FIT_GEAR"):
        w("  cad.%-12s %+.2f mm on diameter" % (k, getattr(cad, k)))
    w("")
    w("WHERE THE RIG DIVERGES FROM WHAT check_drive MODELLED")
    w("  1. The rail is FOUR ARCS, not one, because a pinion's hub reaches")
    w("     into the flange's band.  A pinion fills its own window, so the")
    w("     only true dead arc is still the mouth's %.2f deg, against the"
      % Ring.race_mouth())
    w("     120 deg capture_wander was bounded at.")
    w("  2. A printed ring weighs about %.1f g against Ring.MASS = %.0f g.  It"
      % (rows[0]["vol"] * 1.1e-3, Ring.MASS))
    w("     matters less than it looks: check_drive measures the inertial")
    w("     share of the demand at 1e-4 N.m against the thread's 0.0220, so a")
    w("     lighter ring makes the torque figure conservative, not wrong.")
    w("  3. The standoff circle (r %.2f) and the pinion circle (r %.2f) are"
      % (cad.STANDOFF_R, M.centre))
    w("     0.125 mm apart, because a 6 mm bonding pad has to sit wholly on")
    w("     the skirt.  The two holes are 2.95 PRESS and 3.40 CLEARANCE and")
    w("     they look identical, so plate.dxf LABELS them.  Read the labels.")
    w("  4. The plate is LOCATED by its two tabs and is not yet FIXED by")
    w("     them: add two corner brackets or a fillet of adhesive, or it")
    w("     pivots about the line of the tabs.")
    w("")
    w("BUILD NOTES")
    w("  1. Print the ring and the pinions in RESIN.  Print the rail arcs in")
    w("     FOUR clearance variants by scaling the channel: %.2f is the spec's"
      % Ring.RACE_CLEAR)
    w("     fit, and check_drive claims the design turns from 0.05 to 0.20.")
    w("     Which of the four turns IS the measurement; print all four.")
    w("  2. Bond the standoffs to the rail's skirt with the ring ASSEMBLED and")
    w("     held concentric.  Four separately-mounted arcs have no common")
    w("     register but the ring itself, so use the ring as the register.")
    w("  3. Bond the V-blocks to the base against the scribe lines, with the")
    w("     ring assembled: the scribe says where, the ring says whether.")
    w("  4. The pinion phase is SET, not printed: mesh each pinion against the")
    w("     ring, then tension the belt, then bond the motor pulley.  One")
    w("     pinion a quarter of a pitch out jams the drive (check_drive).")
    w("  5. Mark the ring, film the run, count turns against commanded steps.")
    w("     A lost tooth is the fault this rig exists to find.")
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
